### ISSUE TITLE
Create source adapter for Albert

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/university#9]
For the time being, we will be scraping data from Albert. This issue is to create a service that scrapes data from Albert, and exposes a JSON API, conforming to the spec described in yacs-rcos/hamilton#3.

It should be noted that as of this writing (3/19/18), the spec is subject to minor changes.

Because there is such a large amount of data to parse through, the adapter service should probably poll Albert on a fixed interval and store the records in memory, rather than load them on demand.

A new repository should be created for this adapter. Issues for the minimum viable implementation should be created and added here as subtasks.

This issue can be marked complete when the following subtasks are completed:
- [x] ~Create a repository~ Done: [adapter-albert-nyu](https://github.com/YACS-RCOS/adapter-albert-nyu)
- [x] Decide what language the service will be written in
- [ ] (add issues from Albert adapter repo here)
  - [ ] Create first iteration of Albert scraper: https://github.com/YACS-RCOS/adapter-albert-nyu/issues/1

**Comment by Bad-Science** [comment]
Repo created: [adapter-albert-nyu](https://github.com/YACS-RCOS/adapter-albert-nyu).
